project_id = "sfdudueswogeusuofbbi"

[functions.verify-recaptcha]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.security-email]
verify_jwt = true

[functions.hash-pin]
verify_jwt = true
